
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 9090
